### ISSUE TITLE
Домашка №1, HTML

### ISSUE THREAD

**Issue by tiny-kottan** [Dmitriy-Yarygin/kottans-js-2016#2]
Разметить эту страницу: https://habrahabr.ru/post/244929/
от вас ожидаеться `.html` файл с семантичной разметкой, без css/js
крупные части контента копипастить не стоит (саму статью, там `h*`/`p`/`code` -- все просто), а вот остальное -- нужно
как должно выглядить

`````` html
<!doctype html>
<html lang=ru>
<meta charset=utf-8>
<title>Habrahabr.ru</title>
<header>
  <ul>
    <li><a href=...>TM Feed</a>
    <li><a>Хабрахабр</a>
  </ul>```
``````

**Comment by Dmitriy-Yarygin** [comment]
https://github.com/Dmitriy-Yarygin/kottans-js-2016/blob/master/week01/%D0%94%D0%BE%D0%BC%D0%B0%D1%88%D0%BA%D0%B0%20%E2%84%961%2C%20HTML%20(%232)/%D0%94%D0%B5%D1%81%D1%8F%D1%82%D1%8C.....%D0%A5%D0%B0%D0%B1%D1%80%D0%B0%D1%85%D0%B0%D0%B1%D1%80.html
